// V1_Angular/src/app/components/add-product/add-product.component.ts
import { Component, OnInit } from '@angular/core';
import { Product } from 'src/app/models/product.model';
import { ProductService } from 'src/app/services/product.service';

@Component({
  selector: 'app-add-product',
  templateUrl: './add-product.component.html',
  styleUrls: ['./add-product.component.css']
})
export class AddProductComponent implements OnInit {

  product: Product = {
    nom : "",
    description : "",
    prix : 0.00,
  };
  submitted = false;

  constructor(private productService: ProductService) { }

  ngOnInit(): void {
  }

  saveProduct(): void {
    const data = {
        data: {
        nom: this.product.nom,
        description: this.product.description,
        prix: this.product.prix,
      }
    };
    console.log(data);
    

    this.productService.create(data)
      .subscribe({
        next: (res) => {
          console.log(res);
          this.submitted = true;
        },
        error: (e) => console.error(e)
      });
  }

  newProduct(): void {
    this.product = {
      nom: "",
      description: "",
      prix: 0.00,
    };
  }

}

<div>
  <div class="submit-form">
    <div *ngIf="!submitted">
      <div class="form-group">
        <label for="title">Title</label>
        <input
          type="text"
          class="form-control"
          id="title"
          required
          [(ngModel)]="product.nom"
          name="title"
        />
      </div>

      <div class="form-group">
        <label for="description">Description</label>
        <input
          class="form-control"
          id="description"
          required
          [(ngModel)]="product.description"
          name="description"
        />
      </div>

      <div class="form-group">
        <label for="description">Prix</label>
        <input
          class="form-control"
          id="description"
          required
          [(ngModel)]="product.prix"
          name="prix"
        />
      </div>

      <button (click)="saveProduct()" class="btn btn-success">Submit</button>
    </div>

    <div *ngIf="submitted">
      <h4>✅ Product was submitted successfully!</h4>
    </div>
  </div>
</div>

// V1_Vue/src/components/AddProduct.vue
<template>
  <div class="submit-form">
    <div v-if="!submitted">
      <div class="form-group">
        <label for="nom">Nom</label>
        <input
          type="text"
          class="form-control"
          id="nom"
          required
          v-model="product.nom"
          name="nom "
        />
      </div>

      <div class="form-group">
        <label for="description">Description</label>
        <input
          class="form-control"
          id="description"
          required
          v-model="product.description"
          name="description"
        />
      </div>

      <div class="form-group">
        <label for="description">Prix</label>
        <input
          class="form-control"
          id="prix"
          required
          v-model="product.prix"
          name="prix"
        />
      </div>

      <button @click="saveProduct" class="btn btn-success">Submit</button>
    </div>

    <div v-else>
      <h4>You submitted successfully!</h4>
      <button class="btn btn-success" @click="newProduct">Add</button>
    </div>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import ProductDataService from "../services/ProductDataService";
import Product from "../types/Product";

@Component
export default class AddProduct extends Vue {
  private product: Product = {
    id_produit: 0,
    nom: "",
    description: "",
    date_in: new Date(),
    date_up: new Date(),
    prix: 0,
  };

  private submitted: boolean = false;

  saveProduct() {
    let data = {
      data : {
      nom: this.product.nom,
      description: this.product.description,
      prix: this.product.prix,
    }
    };
    console.log(data);
    

    ProductDataService.create(data)
      .then((response) => {
        this.product.id_produit = response.data.id_produit;
        console.log(response.data);
        this.submitted = true;
      })
      .catch((e) => {
        console.log(e);
      });
  }

  newProduct() {
    this.submitted = false;
    this.product = {} as Product;
  }
}
</script>

<style scoped>
.submit-form {
  max-width: 300px;
  margin: auto;
}
</style>
