// V1_Angular/src/app/components/update-product/update-product.component.ts
import { Component, OnInit } from '@angular/core';
import { Product } from 'src/app/models/product.model';
import { ProductService } from 'src/app/services/product.service';
import { Router } from '@angular/router';


@Component({
  selector: 'app-update-product',
  templateUrl: './update-product.component.html',
  styleUrls: ['./update-product.component.css']
})
export class UpdateProductComponent implements OnInit {

  product: Product = {
    nom : "",
    description : "",
    prix : 0.00,
  };
  submitted = false;
  id!: string;


  constructor(private productService: ProductService, private router: Router) { }

  ngOnInit(): void {
    this.id = this.router.url.split('/')[2];
    this.productService.get(this.id)
    .subscribe({
      next: (data) => {
          this.product = data;        
      },
      error: (e) => console.error(e)
    });
    
  }

  updateProduct(): void {
    const data = {
        data: {
        nom: this.product.nom,
        description: this.product.description,
        prix: this.product.prix,
        id_produit: this.product.id_produit,
      }
    };
    console.log(data);
    

    this.productService.update(data)
      .subscribe({
        next: (res) => {
          console.log(res);
          this.submitted = true;
        },
        error: (e) => console.error(e)
      });
  }

  newProduct(): void {
    this.product = {
      nom: "",
      description: "",
      prix: 0.00,
    };
  }

}

<div>
  <div class="submit-form">
    <div *ngIf="!submitted">
      <div class="form-group">
        <label for="title">Title</label>
        <input
          type="text"
          class="form-control"
          id="title"
          required
          [(ngModel)]="product.nom"
          name="title"
        />
      </div>

      <div class="form-group">
        <label for="description">Description</label>
        <input
          class="form-control"
          id="description"
          required
          [(ngModel)]="product.description"
          name="description"
        />
      </div>

      <div class="form-group">
        <label for="description">Prix</label>
        <input
          class="form-control"
          id="description"
          required
          [(ngModel)]="product.prix"
          name="prix"
        />
      </div>

      <button (click)="updateProduct()" class="btn btn-success">Submit</button>
    </div>

    <div *ngIf="submitted">
      <h4>✅ Product successfully update !</h4>
    </div>
  </div>
</div>

// V1_Vue/src/components/UpdateProduct.vue
<template>
  <div class="edit-form">
    <h4>Product</h4>
    <form>
      <div class="form-group">
        <label for="title">Title</label>
        <input
          type="text"
          class="form-control"
          id="title"
          v-model="currentProduct.nom"
        />
      </div>
      <div class="form-group">
        <label for="description">Description</label>
        <input
          type="text"
          class="form-control"
          id="description"
          v-model="currentProduct.description"
        />
      </div>
        <div class="form-group">
        <label for="prix">Prix</label>
        <input
          type="text"
          class="form-control"
          id="prix"
          v-model="currentProduct.prix"
        />
      </div>
    </form>

    <button type="submit" class="btn btn-primary" @click="updateProduct">
      Update
    </button>
    <p>{{ message }}</p>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import ProductDataService from "../services/ProductDataService";
import Product from "../types/Product";

@Component
export default class ProductDetails extends Vue {
  private currentProduct = {} as Product;
  private message: string = "";
  $route: any;

  getProduct(id: string) {
    ProductDataService.get(id)
      .then((response) => {
        this.currentProduct = response.data;
        console.log(response.data);
      })
      .catch((e) => {
        console.log(e);
      });
  }

  updateProduct() {
    var data = {
      data: {
        id_produit: this.currentProduct.id_produit,
        nom: this.currentProduct.nom,
        description: this.currentProduct.description,
        prix: this.currentProduct.prix,
      },
    }    
    
    ProductDataService.update(data)
      .then((response) => {
        console.log(response.data);
        this.message = "The Product was updated successfully!";
      })
      .catch((e) => {
        console.log(e);
      });
  }

  mounted() {
    this.message = "";
    this.getProduct(this.$route.params.id);
  }
}
</script>

<style scoped>
.edit-form {
  max-width: 300px;
  margin: auto;
}
</style>
