// V1_Angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { MatDialog } from  '@angular/material/dialog';
import { AddProductComponent } from './components/add-product/add-product.component';


@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'Angular CRUD Product';
  // constructor(private  dialogRef : MatDialog) { }
  // openAddDialog(){
  //   this.dialogRef.open(AddProductComponent);
  // }

  

}

<div>
  <nav class="navbar navbar-expand navbar-dark bg-dark">
    <a href="#" class="navbar-brand">Angular CRUD</a>
    <div class="navbar-nav mr-auto">
      <li class="nav-item">
        <a routerLink="product" class="nav-link">Products</a>
      </li>
      <li class="nav-item">
        <a routerLink="add" class="nav-link">Add</a>
      </li>
    </div>
  </nav>

  <div class="container mt-3">
    <router-outlet></router-outlet>
  </div>
</div>

// V1_Vue/src/App.vue
<template>
  <div id="app">
    <nav class="navbar navbar-expand navbar-dark bg-dark">
      <a href="#" class="navbar-brand">Vue CRUD</a>
      <div class="navbar-nav mr-auto">
        <li class="nav-item">
          <a href="/products" class="nav-link">Products</a>
        </li>
        <li class="nav-item">
          <a href="/add" class="nav-link">Add</a>
        </li>
      </div>
    </nav>

    <div class="container mt-3">
      <router-view />
    </div>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";

@Component
export default class App extends Vue {}
</script>
